name: Auto Commit, Issue, and PR

on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch:

jobs:
  auto-tasks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}  

      - name: Set Git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Update or create daily-log.txt
        run: |
          FILE="daily-log.txt"
          if [ ! -f "$FILE" ]; then
            echo "# Daily Log" > "$FILE"
          fi
          echo "Updated on $(date -u)" >> "$FILE"

      - name: Commit changes if needed
        run: |
          git add daily-log.txt
          git diff --cached --quiet || git commit -m "chore: daily update $(date -u '+%Y-%m-%d')"
          git push origin main

      - name: Create an issue
        uses: actions/github-script@v7
        with:
          script: |
            const today = new Date().toISOString().slice(0, 10);
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Auto Issue - ${today}`,
              body: `This issue was automatically created on ${today}.`,
            });

      - name: Create pull request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "feat: auto PR for $(date -u '+%Y-%m-%d')"
          branch: "auto/pr-$(date +%s)"  
          title: "Auto PR - $(date -u '+%Y-%m-%d')"
          body: "This pull request was automatically created by GitHub Actions."
          push: true 
