name: Auto Contribution Actions

on:
  schedule:
    - cron: '0 12 * * *' 
  workflow_dispatch:  

jobs:
  auto-tasks:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - name: Set up job
        run: echo "Starting auto-contribution tasks..."

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  

      - name: Set Git config
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"

      - name: Update or create daily-log.txt
        run: |
          echo "Updated on: $(date -u '+%Y-%m-%d %H:%M:%S UTC')" >> daily-log.txt
          echo "Current run number: ${{ github.run_number }}" >> daily-log.txt

      - name: Create an issue
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.MY_GITHUB_TOKEN }}
          script: |
            const issueTitle = `Daily Report: ${new Date().toISOString().split('T')[0]}`;
            const issueBody = `
            # Daily Contribution Report
            
            - Date: ${new Date().toISOString().split('T')[0]}
            - Run Number: ${process.env.GITHUB_RUN_NUMBER}
            
            This issue was automatically created by the auto-contrib-bot.
            `;
            
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: issueTitle,
              body: issueBody
            });

      - name: Create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          commit-message: "chore: daily update $(date -u '+%Y-%m-%d')"
          title: "Daily Update: $(date -u '+%Y-%m-%d')"
          body: |
            # Automated Daily Update
            
            This PR was automatically created by the auto-contrib-bot.
            
            ## Changes:
            - Updated daily logs
            - Added today's timestamp
          branch: "daily-update-branch"
          base: "main"
          delete-branch: true
          add-paths: |
            daily-log.txt

      - name: Post Checkout repository
        run: echo "Main tasks completed."
        
      - name: Complete job
        run: echo "Auto-contribution tasks completed successfully!"
