name: Auto Contribution Actions

on:
  schedule:
    - cron: '0 12 * * *'  # Runs at 12:00 UTC every day
  workflow_dispatch:  # Allows manual triggering

jobs:
  auto-tasks:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - name: Set up job
        run: echo "Starting auto-contribution tasks..."

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Full history for better commit messages

      - name: Set Git config
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"

      - name: Get current date
        id: date
        run: echo "TODAY=$(date -u '+%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Update or create daily-log.txt
        run: |
          echo "Updated on: $(date -u '+%Y-%m-%d %H:%M:%S UTC')" >> daily-log.txt
          echo "Current run number: ${{ github.run_number }}" >> daily-log.txt

      - name: Create an issue
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.MY_GITHUB_TOKEN }}
          script: |
            const issueTitle = `Daily Report: ${{ steps.date.outputs.TODAY }}`;
            const issueBody = `
            # Daily Contribution Report
            
            - Date: ${{ steps.date.outputs.TODAY }}
            - Run Number: ${process.env.GITHUB_RUN_NUMBER}
            
            This issue was automatically created by the auto-contrib-bot.
            `;
            
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: issueTitle,
              body: issueBody
            });

      - name: Create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          commit-message: "chore: daily update ${{ steps.date.outputs.TODAY }}"
          title: "Daily Update: ${{ steps.date.outputs.TODAY }}"
          body: |
            # Automated Daily Update
            
            This PR was automatically created by the auto-contrib-bot.
            
            ## Changes:
            - Updated daily logs
            - Added today's timestamp: ${{ steps.date.outputs.TODAY }}
          branch: "daily-update-branch"
          base: "main"
          delete-branch: true
          add-paths: |
            daily-log.txt

      - name: Post Checkout repository
        run: echo "Main tasks completed."
        
      - name: Complete job
        run: echo "Auto-contribution tasks completed successfully!"
