name: Auto Contribution Actions

on:
  schedule:
    - cron: '0 12 * * 1,2,3,4,5'  # Setiap Senin sampai Jumat, jam 12:00 UTC (Commit bisa lebih dari sekali sehari)
    - cron: '0 18 * * 1,2,3,4,5'  # Commit tambahan pada jam 18:00 UTC
    - cron: '0 12 * * 2,4'        # Issue pada Selasa dan Kamis, jam 12:00 UTC
  workflow_dispatch:  # Memungkinkan pemicu manual

jobs:
  auto-tasks:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - name: Memulai tugas auto-kontribusi
        run: echo "Mulai menjalankan tugas auto-kontribusi..."

      - name: Checkout repositori
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ambil seluruh riwayat untuk commit yang lebih detail

      - name: Setel konfigurasi Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"

      - name: Ambil tanggal hari ini
        id: date
        run: echo "TODAY=$(date -u '+%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Perbarui atau buat daily-log.txt
        run: |
          echo "Diperbarui pada: $(date -u '+%Y-%m-%d %H:%M:%S UTC')" >> daily-log.txt
          echo "Nomor run saat ini: ${{ github.run_number }}" >> daily-log.txt

      - name: Buat issue baru (untuk Selasa dan Kamis)
        if: github.event.schedule == '0 12 * * 2,4'  # Issue hanya pada Selasa dan Kamis
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.MY_GITHUB_TOKEN }}
          script: |
            const issueTitle = `Laporan Harian: ${{ steps.date.outputs.TODAY }}`;
            const issueBody = `
            # Laporan Kontribusi Harian
            
            - Tanggal: ${{ steps.date.outputs.TODAY }}
            - Nomor Run: ${process.env.GITHUB_RUN_NUMBER}
            
            Issue ini dibuat otomatis oleh auto-contrib-bot.
            `;
            
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: issueTitle,
              body: issueBody
            });

      - name: Buat pull request (untuk Senin sampai Jumat)
        if: github.event.schedule == '0 12 * * 1,2,3,4,5'  # Commit pada Senin sampai Jumat
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          commit-message: "chore: update harian ${{ steps.date.outputs.TODAY }}"
          title: "Update Harian: ${{ steps.date.outputs.TODAY }}"
          body: |
            # Pembaruan Harian Otomatis
            
            PR ini dibuat otomatis oleh auto-contrib-bot.
            
            ## Perubahan:
            - Diperbarui log harian
            - Ditambahkan timestamp hari ini: ${{ steps.date.outputs.TODAY }}
          branch: "daily-update-branch"
          base: "main"
          delete-branch: true
          add-paths: |
            daily-log.txt

      - name: Selesai checkout repositori
        run: echo "Semua tugas utama selesai."

      - name: Selesai menjalankan tugas
        run: echo "Tugas auto-kontribusi berhasil dijalankan!"
